#!/usr/bin/env python
# pylint: disable=too-many-lines
from datetime import datetime as dt, timedelta
import os
import sys
from typing import List
import requests

import ccxt
from enforce_typing import enforce_types

from predict_eth.helpers import (
    calc_nmse,
    create_alice_wallet,
    create_ocean_instance,
    filter_to_target_uts,
    print_datetime_info,
    target_12_unixtimes
)
from ocean_lib.models.data_nft import DataNFT
from ocean_lib.ocean import crypto

# Set network. Change this one line if needed. *Supposed* to be "polygon-test"
NETWORK_NAME = "polygon-test"  # polygon-test (Mumbai), polygon-main, goerli...

# Auto-calc chainid
NAME_TO_CHAINID = {"polygon-test": 80001, "polygon-main": 137, "goerli": 5}
CHAINID = NAME_TO_CHAINID[NETWORK_NAME]

# Usage instructions
HELP_MAIN = f"""predict-eth-judge

Usage: pej DEADLINE

DEADLINE is the submission deadline.
 - Format is YYYY-MM-DD_HOUR:MIN, in UTC
 - Example for Round 5: 2023-05-03_23:59

Hard-coded values: 
   NETWORK_NAME={NETWORK_NAME}
   CHAINID={CHAINID}

Ennvars expected:
   REMOTE_TEST_PRIVATE_KEY1 (for judges' account)
   POLYGONSCAN_API_KEY
"""


@enforce_types
def get_nft_addresses(deadline_dt):
    a_week_before_deadline = deadline_dt - timedelta(weeks=1)
    judges_address = "0xA54ABd42b11B7C97538CAD7C6A2820419ddF703E"
    
    url = "https://api-testnet.polygonscan.com/api"
    params = {
        "module": "account",
        "action": "tokennfttx",
        "address": judges_address,
        "apikey": os.getenv("POLYGONSCAN_API_KEY"),
    }
    txs = requests.get(url, params=params).json()["result"] # list of "tx"

    #each tx is a dict that includes: {'timeStamp': '1677562009', 'hash': '0x163991c9fb2c94b7452909a1bd8cf4d298d92dc90ef2e49ab13dc935f0552061','from': '0x04815de815db15a3086425b58981545bec018a6a', 'contractAddress': '0x458420a012cb7e63ae24ecf83eb21ab7c40d71d8', 'to': '0xa54abd42b11b7c97538cad7c6a2820419ddf703e', 'tokenID': '1', 'tokenName': 'Data NFT 1', 'tokenSymbol': 'DN1'}

    filtered_txs = [tx
                    for tx in txs
                    if a_week_before_deadline < _date(tx) <= deadline_dt]

    print(f"Judges address = {judges_address}")
    _printTxTimes(txs, "all txs")
    _printTxTimes(filtered_txs, "on-time txs")
    
    addresses = [tx["contractAddress"] for tx in filtered_txs]
    return addresses

@enforce_types
def _printTxTimes(txs, s): 
    print(f"Timestamps for {s} ({len(txs)} total):")
    if len(txs) < 7:
        _print_dates(txs)
    else:
        _print_dates(txs[:3])
        print("...")
        _print_dates(txs[-3:])
    print()

@enforce_types
def _print_dates(txs):
    for tx in txs:
        print(_date(tx).strftime('%Y-%m-%d_%H:%M'))
    
@enforce_types
def _date(tx):
    # must include "utc" in "fromtimestamp", to account for time zone diff
    return dt.utcfromtimestamp(int(tx["timeStamp"]))

@enforce_types
def nft_addr_to_pred_vals(nft_addr: str, ocean, alice) -> List[float]:
    # adapted from "What judges will do" in
    #  https://github.com/oceanprotocol/predict-eth/blob/main/challenges/main4.md

    # get predicted ETH values
    nft = DataNFT(ocean.config_dict, nft_addr)
    pred_vals_str_enc = nft.get_data("predictions")
    try:
        pred_vals_str = crypto.asym_decrypt(pred_vals_str_enc, alice.private_key)
        pred_vals = [float(s) for s in pred_vals_str[1:-1].split(',')]
    except:
        return []

    return pred_vals


def get_cex_vals(deadline_dt):
    target_uts = target_12_unixtimes(deadline_dt+timedelta(minutes=1))
    print_datetime_info("target times", target_uts)

    # get actual ETH values
    cex_x = ccxt.binance().fetch_ohlcv('ETH/USDT', '5m')
    allcex_uts = [xi[0]/1000 for xi in cex_x]    
    allcex_vals = [xi[4] for xi in cex_x]
    print_datetime_info("CEX data info", allcex_uts)
    cex_vals = filter_to_target_uts(target_uts, allcex_uts, allcex_vals)
    print(f"cex ETH price is ${cex_vals[0]} at target time 0")
    print(f"cex_vals: {cex_vals}")

    return cex_vals


def parse_arguments(arguments):
    if len(arguments) != 2:
        print(HELP_MAIN)
        sys.exit(0)

    DEADLINE = arguments[1]
    deadline_dt = dt.strptime(DEADLINE, '%Y-%m-%d_%H:%M')
    deadline_str = deadline_dt.strftime('%Y-%m-%d_%H:%M')

    print("pej: Begin")
    print(f"Args: DEADLINE={deadline_str}")

    return deadline_dt


def print_addresss_nmse(nmses):
    for address, nmse in nmses.items():
        print(f"Address: {address}, NMSE: {nmse}")


def print_results(nmses, bad_nft_addrs):
    print("\n-------------")
    print("Summary:")
    print("-------------")

    print(f"{len(bad_nft_addrs)} bad entries: ")
    for bad_addr in bad_nft_addrs:
        print(f"BAD: {bad_addr}")

    print(f"\n{len(nmses)} good entries:")
    print_addresss_nmse(nmses)

    ranking = {
        k: v for k, v in sorted(nmses.items(), key=lambda item: item[1])
    }
    print("\nafter ranking:")
    print("-------------")
    print_addresss_nmse(ranking)

    print("\ntop 3:")
    print("-------------")
    print("\n".join(list(ranking.keys())[:3]))

    print("\npej: Done")


@enforce_types
def do_getnmses():
    ocean = create_ocean_instance(NETWORK_NAME)
    alice_private_key = os.getenv("REMOTE_TEST_PRIVATE_KEY1")
    assert alice_private_key, "need envvar REMOTE_TEST_PRIVATE_KEY1"
    alice = create_alice_wallet(ocean)  # uses REMOTE_TEST_PRIVATE_KEY1

    deadline_dt = parse_arguments(sys.argv)
    cex_vals = get_cex_vals(deadline_dt)

    entries = get_nft_addresses(deadline_dt)
    n = len(entries)
    nmses, bad_nft_addrs = {}, []

    for i, entry in enumerate(entries):
        nft_addr = entry
        print("="*60)
        print(f"NFT #{i+1}/{n}: Begin.")

        # get predicted ETH values
        print(f"nft_addr: {nft_addr}")
        pred_vals = nft_addr_to_pred_vals(nft_addr, ocean, alice)  # main call
        print(f"pred_vals: {pred_vals}")
        if len(pred_vals) != len(cex_vals):
            print("Error: wrong # predicted values. Skipping")
            bad_nft_addrs.append(nft_addr)
            continue

        # calc nmse, plot
        nmse = calc_nmse(cex_vals, pred_vals)
        print(f"nft_addr={nft_addr}, NMSE = {nmse:.8f}")
        # plot_prices(cex_vals, pred_vals)

        nmses[nft_addr] = nmse
        print(f"NFT #{i+1}/{n}: Done")

    return nmses, bad_nft_addrs


@enforce_types
def do_help():
    print(HELP_MAIN)
    sys.exit(0)


# ========================================================================
# main
@enforce_types
def do_main():
    if len(sys.argv) != 2 or sys.argv[1] == "help":
        do_help()

    else:
        nmses, bad_nft_addrs = do_getnmses()
        print_results(nmses, bad_nft_addrs)


if __name__ == "__main__":
    do_main()
